/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppAddMemory {
    'hideLoading': any;
    'saveSuccessFn': any;
    'showLoading': any;
  }
  interface AppAddMemoryAttributes extends StencilHTMLAttributes {
    'hideLoading'?: any;
    'saveSuccessFn'?: any;
    'showLoading'?: any;
  }

  interface AppGetMemories {
    'hideLoading': any;
    'showLoading': any;
  }
  interface AppGetMemoriesAttributes extends StencilHTMLAttributes {
    'hideLoading'?: any;
    'showLoading'?: any;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppAddMemory': Components.AppAddMemory;
    'AppGetMemories': Components.AppGetMemories;
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-add-memory': Components.AppAddMemoryAttributes;
    'app-get-memories': Components.AppGetMemoriesAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppAddMemoryElement extends Components.AppAddMemory, HTMLStencilElement {}
  var HTMLAppAddMemoryElement: {
    prototype: HTMLAppAddMemoryElement;
    new (): HTMLAppAddMemoryElement;
  };

  interface HTMLAppGetMemoriesElement extends Components.AppGetMemories, HTMLStencilElement {}
  var HTMLAppGetMemoriesElement: {
    prototype: HTMLAppGetMemoriesElement;
    new (): HTMLAppGetMemoriesElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-add-memory': HTMLAppAddMemoryElement
    'app-get-memories': HTMLAppGetMemoriesElement
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-add-memory': HTMLAppAddMemoryElement;
    'app-get-memories': HTMLAppGetMemoriesElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
